import React,{useState,useEffect,useRef,lazy,Suspense} from 'react';import{createRoot}from'react-dom/client';import './style.css';
const Paper=lazy(()=>import('./Paper'));
const maps='https://maps.app.goo.gl/Cq4LRmKaf2C1Zntn9?g_st=ic';
const wa=(service)=>'https://wa.me/6289698617455?text='+encodeURIComponent(service?'Halo Green Salon, saya ingin bertanya dan reservasi layanan '+service+'.':'Halo Green Salon, saya ingin bertanya jadwal dan reservasi perawatan.');
const prices=[['Potong','25.000','Rambut'],['Cuci Ptg Blw','40.000','Rambut'],['Cuci Blow','20.000','Rambut'],['Cat Rambut','90.000','Rambut',1],['Crembat','70.000','Perawatan',1],['Crantin','190.000','Perawatan',1],['Cuci Catok','40.000','Rambut'],['Hirlahit','90.000','Rambut',1],['Serum','50.000','Perawatan'],['Smoting','180.000 / 200.000','Rambut',1],['Ribonding','190.000','Rambut',1],['Hairmusk','45.000','Perawatan'],['Rias','175.000','Wajah'],['Facial','50.000','Wajah'],['Spa Rambut','50.000','Perawatan'],['Kriting','90.000','Rambut'],['Totok Wajah','35.000','Wajah']];
const leaf=<svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M7 25C2 9 13 4 27 5c0 15-10 23-20 20Z" stroke="currentColor" strokeWidth="1.5"/><path d="m5 28 16-16" stroke="currentColor" strokeWidth="1.5"/></svg>;
const chat=<svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M27 15.4A11.2 11.2 0 0 1 10 25l-6 2 2-6A11.2 11.2 0 1 1 27 15.4Z" stroke="currentColor" strokeWidth="1.8"/><path d="m11 10 2 4-1.5 1c1 2 2.4 3.4 4.5 4.5l1.2-1.6 3.8 1.9c-.5 3-3 3-5.5 1.6-3.8-2-6.3-4.9-7-8-.4-1.9.6-3.4 2.5-3.4Z" fill="currentColor"/></svg>;
function External({href,children,className=''}){return <a href={href} className={className} target="_blank" rel="noopener noreferrer">{children}</a>}
function Logo(){return <a href="#home" className="brand" aria-label="Green Salon beranda"><span className="monogram">G<span>{leaf}</span></span><span>Green S<small>GREEN SALON</small></span></a>}
function Experience(){const[enabled,setEnabled]=useState(false);const[visible,setVisible]=useState(false);const holder=useRef(null);useEffect(()=>{const io=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{rootMargin:'80px'});io.observe(holder.current);const onVisibility=()=>{holder.current?.querySelectorAll('iframe').forEach(el=>el.contentWindow?.postMessage({type:'green-paper',active:!document.hidden},'*'))};document.addEventListener('visibilitychange',onVisibility);return()=>{io.disconnect();document.removeEventListener('visibilitychange',onVisibility)}},[]);return <section className="experience" ref={holder}><div className="wrap experience-inner"><div><p className="eyebrow">A LITTLE MOMENT OF WONDER</p><h2>Detail kecil.<br/><em>Kesan yang tinggal.</em></h2><p>Sebuah sentuhan interaktif untuk kamu jelajahi.</p><small>Presentasi dekoratif ThreeUI.</small></div><div className="paper">{enabled&&visible?<Suspense fallback={<p>Memuat pengalaman interaktif…</p>}><Paper/></Suspense>:<button className="paper-start" onClick={()=>setEnabled(true)}>{leaf}<span>Jelajahi kertas 3D</span><small>Ketuk untuk memulai ↗</small></button>}</div></div></section>}
function App(){const[menu,setMenu]=useState(false);const[filter,setFilter]=useState('Semua');const[query,setQuery]=useState('');const list=prices.filter(p=>(filter==='Semua'||p[2]===filter)&&p[0].toLowerCase().includes(query.toLowerCase()));useEffect(()=>{const close=e=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);return <>
<a className="skip" href="#main">Lewati ke konten</a><header><div className="wrap nav"><Logo/><button className="menu-toggle" aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>{menu?'Tutup ✕':'Menu ☰'}</button><nav id="navigation" className={menu?'open':''} aria-label="Navigasi utama">{[['layanan','Layanan'],['harga','Daftar harga'],['lokasi','Lokasi']].map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}<External href={wa()} className="button small">Reservasi ↗</External></nav></div></header>
<main id="main"><section className="hero wrap" id="home"><div className="hero-copy"><p className="eyebrow"><span className="dot"/> PERSONAL CARE, NATURALLY</p><h1>Sedikit waktu<br/>untuk <em>diri sendiri.</em></h1><p className="intro">Selamat datang di Green Salon. Sentuhan perawatan yang personal, untuk menemani harimu dengan lebih nyaman.</p><div className="actions"><External href={wa()} className="button">Buat janji temu <span>↗</span></External><a href="#harga" className="text-link">Lihat daftar harga <span>↓</span></a></div><div className="hero-note">{leaf}<span>Rambut, wajah, dan momen untukmu.</span></div></div><div className="hero-visual"><img src="/assets/botanical.webp" alt="Daun hijau, botol perawatan dan gunting di atas permukaan batu" width="1024" height="1536" fetchPriority="high"/><div className="image-label">THE GREEN SALON EDIT <span>01 / BOTANICAL</span></div><a href="#harga" className="glass-price"><span>POTONG RAMBUT<small>Sentuhan sederhana, terasa berbeda.</small></span><strong>Rp25<span>.000</span></strong><span className="round-arrow">↗</span></a></div></section>
<div className="ribbon"><span>HAIR CARE</span><i>✦</i><span>PERSONAL TOUCH</span><i>✦</i><span>GREEN SALON</span><i>✦</i><span>A MOMENT FOR YOU</span></div>
<section id="layanan" className="wrap section"><div className="section-heading"><div><p className="eyebrow">01 / PILIHAN PERAWATAN</p><h2>Perawatan yang<br/><em>pas untukmu.</em></h2></div><p>Mulai dari potong rambut hingga perawatan wajah. Ceritakan kebutuhanmu, dan tanyakan pilihan layanan melalui WhatsApp.</p></div><div className="service-cards">{[['✂','Rambut','Potong, cuci, styling, dan warna. Pilih sentuhan yang kamu inginkan.','Mulai Rp20.000'],['❋','Perawatan','Crembat, hairmusk, dan spa rambut. Luangkan waktu untuk merawat diri.','Mulai Rp45.000'],['✧','Wajah','Facial, totok wajah, dan rias untuk melengkapi kebutuhan perawatanmu.','Mulai Rp35.000']].map(([icon,title,desc,price])=><a href="#harga" className="service-card" key={title} onClick={()=>setFilter(title)}><span className="service-icon">{icon}</span><span className="card-number">0{['Rambut','Perawatan','Wajah'].indexOf(title)+1}</span><h3>{title}</h3><p>{desc}</p><div><span>{price}</span><span>↗</span></div></a>)}</div></section>
<section id="harga" className="price-section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">02 / DAFTAR HARGA</p><h2>Kenali layanan.<br/><em>Temukan pilihan.</em></h2></div><p>Harga ditampilkan langsung agar mudah dibaca. Untuk layanan bertanda “mulai”, tanyakan harga akhir sebelum reservasi.</p></div><div className="price-tools"><div className="filters" aria-label="Kategori layanan">{['Semua','Rambut','Perawatan','Wajah'].map(cat=><button key={cat} aria-pressed={filter===cat} onClick={()=>setFilter(cat)}>{cat}</button>)}</div><label className="search"><span aria-hidden="true">⌕</span><input type="search" placeholder="Cari layanan…" aria-label="Cari layanan" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="price-list" aria-live="polite">{list.map(([name,price,cat,from])=><External key={name} href={wa(name)} className="price-row"><span><strong>{name}</strong><small>{cat}</small></span><span className="price"><small>{from?'Mulai dari':''}</small><b>Rp{price}</b></span><span className="price-arrow">↗</span></External>)}</div>{!list.length&&<p className="empty">Layanan tidak ditemukan. Coba kata lain atau pilih Semua.</p>}<div className="price-foot"><span>Nama layanan mengikuti daftar harga salon.</span><External href={wa()}>Ada pertanyaan? Chat kami ↗</External></div></div></section>
<Experience/>
<section id="lokasi" className="wrap section location"><div><p className="eyebrow">03 / SAMPAI BERTEMU</p><h2>Temukan<br/><em>Green Salon.</em></h2><p>Buka petunjuk arah untuk menuju lokasi salon. Sebelum berkunjung, hubungi kami untuk memastikan jadwal yang tersedia.</p><div className="actions"><External href={maps} className="button">Buka Google Maps ↗</External></div><External href={maps} className="review-link">Lihat ulasan pelanggan di Google ↗</External></div><div className="location-card"><span className="location-mark">{leaf}</span><p className="eyebrow">LET’S MAKE TIME</p><h3>Perawatan berikutnya<br/>dimulai dari satu pesan.</h3><p>Tanyakan layanan, harga, dan ketersediaan jadwal langsung kepada kami.</p><External href={wa()} className="contact-line">{chat}<span>WhatsApp<small>+62 896-9861-7455</small></span><span>↗</span></External></div></section>
<section className="booking"><div className="wrap"><p className="eyebrow">YOUR MOMENT, YOUR PACE</p><h2>Saatnya memberi waktu<br/><em>untuk dirimu.</em></h2><External href={wa()} className="button light">Reservasi via WhatsApp ↗</External><span className="booking-leaf">{leaf}</span></div></section>
</main><footer className="wrap"><Logo/><p>Perawatan personal. Sentuhan Green Salon.</p><span>© {new Date().getFullYear()} Green Salon</span></footer><External href={wa()} className="floating-wa">{chat}<span>Chat WhatsApp</span></External></>}
createRoot(document.getElementById('root')).render(<App/>);
